version: '3.8'

services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    network_mode: "host"  # Use host networking for Home Assistant
    volumes:
      - ./config:/config  # Mount configuration directory
    environment:
      - TZ=America/New_York  # Set your timezone
    restart: unless-stopped
